[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  # Disable secrets scanning for Next.js public environment variables
  SECRETS_SCAN_ENABLED = "false"
  # Ensure Next.js can access environment variables during build
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

# Ensure environment variables are available at runtime
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
